// AUTO-GENERATED by scripts/align-voiceover.mjs — do not edit by hand.
// Exact narration timings from ElevenLabs forced alignment.

export type TimedChunk = { text: string; from: number; to: number };

export const SUBTITLES: Record<string, TimedChunk[]> = {
  "scene-01": [
    {
      "text": "Welcome to Global Chemicals and Maintenance Systems LLC, Al Barami Group of Companies.",
      "from": 0.72,
      "to": 6.01
    },
    {
      "text": "Today, we'll introduce you to the key safety guidelines and best practices to ensure your safety while working with us.",
      "from": 6.52,
      "to": 12.65
    },
    {
      "text": "Safety is everyone's responsibility.",
      "from": 13.18,
      "to": 15.23
    }
  ],
  "scene-02": [
    {
      "text": "GCMS, over the last four decades, has been actively associated with Power and Water and Wastewater industries —",
      "from": 0.76,
      "to": 8.05
    },
    {
      "text": "life's most essentials in the Sultanate of Oman.",
      "from": 8.1,
      "to": 10.85
    },
    {
      "text": "Established in 1963, and becoming a 100% Omani company in the year 1976,",
      "from": 11.46,
      "to": 17.85
    },
    {
      "text": "it became a member of Al Barami Group of Companies.",
      "from": 17.9,
      "to": 20.69
    },
    {
      "text": "GCMS handles the entire spectrum of the project lifecycle, which includes BOOT — Build, Own, Operate and Transfer —",
      "from": 21.36,
      "to": 29.81
    },
    {
      "text": "Engineering, Procurement, Construction, Testing, Commissioning, Operation and Maintenance,",
      "from": 29.86,
      "to": 35.53
    },
    {
      "text": "and Facilities Management, across Power, Water and Wastewater and Renewable Energy.",
      "from": 35.58,
      "to": 40.79
    },
    {
      "text": "GCMS currently has a workforce of more than one thousand five hundred people,",
      "from": 41.7,
      "to": 46.11
    },
    {
      "text": "spread across all regions of the Sultanate of Oman.",
      "from": 46.16,
      "to": 48.95
    },
    {
      "text": "GCMS is committed to being a leader in Quality, Health, Safety and Environmental Protection,",
      "from": 49.5,
      "to": 55.41
    },
    {
      "text": "conducting its business with the utmost emphasis on the safety of its people,",
      "from": 55.46,
      "to": 59.59
    },
    {
      "text": "its processes, and the well-being of the communities and stakeholders.",
      "from": 59.64,
      "to": 63.43
    }
  ],
  "scene-03": [
    {
      "text": "GCMS is approved as a Grade A Electrical and Solar Contractor by the Distribution Code Review Panel.",
      "from": 0.74,
      "to": 6.97
    },
    {
      "text": "We are registered on the Joint Supplier Registration System for Oil and Gas, and GCMS is a member of OPAL.",
      "from": 7.3,
      "to": 13.71
    },
    {
      "text": "GCMS is certified with the ISO QHSE Management Systems 9001,",
      "from": 14.3,
      "to": 19.99
    },
    {
      "text": "14001 and 45001, and is registered as Excellent Grade with the Tender Board.",
      "from": 20.04,
      "to": 25.79
    }
  ],
  "scene-04": [
    {
      "text": "Before we go any further, let me introduce you to the fact that you're our top priority,",
      "from": 0.7,
      "to": 5.45
    },
    {
      "text": "and safety is our first priority in our daily working hours —",
      "from": 5.5,
      "to": 9.27
    },
    {
      "text": "whether you're a visitor, contractor, industry vendor, or on your first job.",
      "from": 9.32,
      "to": 13.77
    },
    {
      "text": "It is important that everyone has the knowledge to make the right decisions to stay safe.",
      "from": 14.26,
      "to": 18.51
    }
  ],
  "scene-05": [
    {
      "text": "Here are a few simple rules to get your visit starting off right.",
      "from": 0.7,
      "to": 3.97
    },
    {
      "text": "Please ensure that your visitor pass is visible at all times, and return it when you leave.",
      "from": 4.56,
      "to": 9.53
    },
    {
      "text": "Your safety is your responsibility, and our host will assist you — please feel free to ask them any questions.",
      "from": 10.3,
      "to": 17.13
    },
    {
      "text": "To protect company property, assets and privacy, photographs and video can only be taken with prior approval.",
      "from": 17.58,
      "to": 24.21
    }
  ],
  "scene-06": [
    {
      "text": "Before you start, it's essential to wear the correct Personal Protective Equipment, or PPE.",
      "from": 0.7,
      "to": 5.75
    },
    {
      "text": "Your safety gear will help protect you from potential hazards.",
      "from": 6.26,
      "to": 9.27
    },
    {
      "text": "Always check your PPE before starting work.",
      "from": 9.82,
      "to": 12.47
    }
  ],
  "scene-07": [
    {
      "text": "Know the emergency exits and the locations of safety equipment,",
      "from": 0.72,
      "to": 4.05
    },
    {
      "text": "such as fire extinguishers, first-aid kits, and emergency assembly points.",
      "from": 4.1,
      "to": 8.41
    },
    {
      "text": "In case of emergency, follow the evacuation plan.",
      "from": 8.88,
      "to": 11.77
    }
  ],
  "scene-08": [
    {
      "text": "Identifying hazards is the first step in preventing accidents.",
      "from": 0.7,
      "to": 3.97
    },
    {
      "text": "Always be alert about potential risks in your work area.",
      "from": 4.48,
      "to": 7.53
    },
    {
      "text": "Report any hazards immediately to your supervisor.",
      "from": 8.18,
      "to": 10.91
    }
  ],
  "scene-09": [
    {
      "text": "Follow safe work practices at all times.",
      "from": 0.7,
      "to": 3.01
    },
    {
      "text": "Always read signs and instructions carefully.",
      "from": 3.28,
      "to": 5.61
    },
    {
      "text": "When lifting, use your legs, not your back.",
      "from": 6.22,
      "to": 8.51
    }
  ],
  "scene-10": [
    {
      "text": "GCMS's twelve Golden Life Saving Rules are a set of concise commitment statements,",
      "from": 0.74,
      "to": 6.11
    },
    {
      "text": "carefully designed to ensure that workers work safely and return safely to their loved ones.",
      "from": 6.16,
      "to": 11.09
    },
    {
      "text": "Rule one — Life of Line: protect yourself by complying with HSE rules.",
      "from": 11.72,
      "to": 16.65
    },
    {
      "text": "Rule two — Public Safety: safeguard the public from significant hazards.",
      "from": 17.14,
      "to": 21.53
    },
    {
      "text": "Rule three — Traffic Safety: always adhere to road safety rules.",
      "from": 22.06,
      "to": 26.21
    },
    {
      "text": "Rule four — Electrical Safety: follow the Electrical Safety Rules without fail.",
      "from": 26.84,
      "to": 31.53
    },
    {
      "text": "Rule five — Lifting Safety: no lifting activities are allowed without a Permit to Work.",
      "from": 32.16,
      "to": 37.71
    },
    {
      "text": "Rule six — Excavation Safety: no excavation activities are allowed without a Permit to Work.",
      "from": 38.16,
      "to": 45.39
    },
    {
      "text": "Rule seven — Hot Work Safety: ensure fire protection measures are in place before starting hot work.",
      "from": 45.44,
      "to": 51.27
    },
    {
      "text": "Rule eight — Work at Height: always wear a full-body safety harness when working above one and a half meters.",
      "from": 51.76,
      "to": 57.89
    },
    {
      "text": "Rule nine — Confined Space Safety: no confined space activities are allowed without a Permit to Work.",
      "from": 58.42,
      "to": 65.07
    },
    {
      "text": "Rule ten — Radiography Work Safety: no radiography activities are permitted without a Permit to Work.",
      "from": 65.54,
      "to": 72.33
    },
    {
      "text": "Rule eleven —",
      "from": 73.18,
      "to": 74.11
    },
    {
      "text": "No drugs, alcohol, or smoking: drugs and alcohol are strictly prohibited while on task and on company premises.",
      "from": 74.16,
      "to": 80.85
    },
    {
      "text": "Rule twelve — Personal Protective Equipment: it is essential to wear the correct PPE before starting work.",
      "from": 81.32,
      "to": 87.57
    },
    {
      "text": "The twelve Golden Life Saving Rules pocketbook is distributed to every employee in their preferred language —",
      "from": 88.06,
      "to": 93.83
    },
    {
      "text": "English, Arabic, Hindi, Urdu and Bangla.",
      "from": 93.88,
      "to": 97.19
    }
  ],
  "scene-11": [
    {
      "text": "Report any incidents or near-misses.",
      "from": 0.68,
      "to": 3.03
    },
    {
      "text": "Reporting helps prevent future accidents.",
      "from": 3.52,
      "to": 5.87
    },
    {
      "text": "Near misses are incidents that could have resulted in injury — report them!",
      "from": 6.32,
      "to": 10.47
    }
  ],
  "scene-12": [
    {
      "text": "Safety is a team effort.",
      "from": 0.72,
      "to": 2.05
    },
    {
      "text": "Let's work together to ensure everyone stays safe on the job.",
      "from": 2.56,
      "to": 5.69
    },
    {
      "text": "Safety first — always!",
      "from": 6.24,
      "to": 8.07
    }
  ],
  "scene-13": [
    {
      "text": "Thank you for completing your HSE induction.",
      "from": 0.7,
      "to": 3.15
    },
    {
      "text": "For any questions or concerns about safety, please speak with your supervisor.",
      "from": 3.7,
      "to": 8.35
    },
    {
      "text": "Stay safe!",
      "from": 8.4,
      "to": 9.15
    }
  ]
};

export const RULE_TIMINGS: { from: number; to: number }[] = [
  {
    "from": 11.72,
    "to": 16.65
  },
  {
    "from": 17.14,
    "to": 21.53
  },
  {
    "from": 22.06,
    "to": 26.21
  },
  {
    "from": 26.84,
    "to": 31.53
  },
  {
    "from": 32.16,
    "to": 37.71
  },
  {
    "from": 38.16,
    "to": 45.55
  },
  {
    "from": 45.44,
    "to": 51.27
  },
  {
    "from": 51.76,
    "to": 57.89
  },
  {
    "from": 58.42,
    "to": 65.07
  },
  {
    "from": 65.54,
    "to": 72.33
  },
  {
    "from": 73.18,
    "to": 74.31
  },
  {
    "from": 81.32,
    "to": 87.57
  }
];
